from __future__ import annotations

import subprocess
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
WEB = ROOT / "src" / "auto_research" / "evidence" / "web"


class FusionPaneResizeRuntimeTests(unittest.TestCase):
    def test_v2_snap_restore_pointer_keyboard_and_responsive_groups(self) -> None:
        program = f"""
const fs=require('fs'),assert=require('assert'),memory=new Map();
class Classes{{constructor(){{this.values=new Set()}}add(v){{this.values.add(v)}}remove(v){{this.values.delete(v)}}toggle(v,on){{on?this.values.add(v):this.values.delete(v)}}contains(v){{return this.values.has(v)}}}}
class El{{constructor(kind=''){{this.dataset=kind?{{paneSeparator:kind}}:{{}};this.hidden=false;this.classList=new Classes();this.attrs={{}};this.listeners={{}};this.captured=null;this.innerHTML='';}}setAttribute(k,v){{this.attrs[k]=String(v)}}removeAttribute(k){{delete this.attrs[k]}}addEventListener(k,fn){{(this.listeners[k]??=[]).push(fn)}}setPointerCapture(id){{this.captured=id}}hasPointerCapture(id){{return this.captured===id}}releasePointerCapture(id){{assert.equal(this.captured,id);this.captured=null}}focus(){{}}}}
class RenderEl extends El{{constructor(){{super();this.renderCount=0;this._html='';}}set innerHTML(value){{this._html=String(value);this.renderCount=(this.renderCount||0)+1}}get innerHTML(){{return this._html}}}}
const contextSep=new El('context'),groupSep=new El('editor-groups'),inspectorSep=new El('inspector'),context=new El(),inspector=new El(),primary=new El(),secondary=new El(),layout=new El(),tabGroups=new El(),primaryTabs=new RenderEl(),secondaryTabs=new RenderEl(),primaryGroup=new El(),secondaryGroup=new El(),contextToggle=new El(),inspectorToggle=new El(),primaryToggle=new El(),secondaryToggle=new El(),contextTitle=new El(),breadcrumb=new El(),primaryLabel=new El(),detailLabel=new El(),statusContext=new El(),inspectorTitle=new El(),inspectorBody=new El(),editor=new El(),html={{dataset:{{}},style:{{values:{{}},setProperty(k,v){{this.values[k]=v}}}}}},body={{dataset:{{view:'paper'}}}};
const ids={{'#fusion-context-separator':contextSep,'#fusion-editor-group-separator':groupSep,'#fusion-inspector-separator':inspectorSep,'#fusion-context':context,'#fusion-inspector':inspector,'#fusion-primary-editor-surface':primary,'#fusion-secondary-editor-surface':secondary,'#fusion-editor-group-content':layout,'#fusion-document-tab-groups':tabGroups,'#fusion-document-tabs-primary':primaryTabs,'#fusion-document-tabs-secondary':secondaryTabs,'#fusion-context-title':contextTitle,'#fusion-breadcrumb':breadcrumb,'#fusion-primary-tab-label':primaryLabel,'#fusion-detail-tab-label':detailLabel,'#fusion-status-context':statusContext,'#fusion-inspector-title':inspectorTitle,'#fusion-inspector-body':inspectorBody,'#fusion-editor':editor}};
const byKind={{'[data-pane-separator="context"]':contextSep,'[data-pane-separator="editor-groups"]':groupSep,'[data-pane-separator="inspector"]':inspectorSep,'[data-document-group="primary"]':primaryGroup,'[data-document-group="secondary"]':secondaryGroup}};
const globalListeners={{}};globalThis.addEventListener=(kind,fn)=>{{(globalListeners[kind]??=[]).push(fn)}};
globalThis.document={{readyState:'loading',documentElement:html,body,querySelector:s=>ids[s]||byKind[s]||null,querySelectorAll:s=>s==='[data-pane-separator]'?[contextSep,groupSep,inspectorSep]:s==='[data-pane-toggle="context"]'?[contextToggle]:s==='[data-pane-toggle="inspector"]'?[inspectorToggle]:s==='[data-pane-toggle="primary"]'?[primaryToggle]:s==='[data-pane-toggle="secondary"]'?[secondaryToggle]:[],addEventListener:()=>{{}}}};
globalThis.localStorage={{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)}};globalThis.innerWidth=1600;
eval(fs.readFileSync({str(WEB / 'document_tab_store.js')!r},'utf8'));eval(fs.readFileSync({str(WEB / 'pane_layout_controller.js')!r},'utf8'));eval(fs.readFileSync({str(WEB / 'workspace_layout_controller.js')!r},'utf8'));eval(fs.readFileSync({str(WEB / 'fusion_review.js')!r},'utf8'));
const api=globalThis.AutoResearchFusion,tabs=api.documentTabs,controller=api.paneController,prevent=()=>{{}};
tabs.open({{tabId:'evidence:a',kind:'evidence',ownerView:'paper',title:'A',identity:{{sourceScope:'workspace',entityType:'table',entityUid:'1'}}}},{{pin:true}});tabs.open({{tabId:'evidence:b',kind:'evidence',ownerView:'paper',title:'B',identity:{{sourceScope:'workspace',entityType:'table',entityUid:'2'}}}},{{groupId:'secondary',pin:true}});
api.bindPaneSeparators();let geometry=api.applyPaneLayout();assert.equal(groupSep.hidden,false);assert.equal(contextSep.attrs['aria-valuemin'],'0');assert.equal(inspectorSep.attrs['aria-valuemin'],'0');
const beforeMoveRender=primaryTabs.renderCount+secondaryTabs.renderCount;contextSep.listeners.pointerdown[0]({{currentTarget:contextSep,button:0,pointerId:7,clientX:300,preventDefault:prevent}});contextSep.listeners.pointermove[0]({{pointerId:7,clientX:80,preventDefault:prevent}});assert.equal(primaryTabs.renderCount+secondaryTabs.renderCount,beforeMoveRender,'pointermove must not rebuild editor tabs');contextSep.listeners.pointerup[0]({{pointerId:7,preventDefault:prevent}});assert(primaryTabs.renderCount+secondaryTabs.renderCount>beforeMoveRender,'pointerup may render once after geometry is stable');assert.equal(api.paneLayout.context.collapsed,true);assert.equal(api.paneLayout.context.size,0);assert.equal(contextSep.hidden,true);assert.equal(html.dataset.paneResizing,undefined);
assert(api.togglePane('context'));assert.equal(api.paneLayout.context.collapsed,false);assert.equal(api.paneLayout.context.size,244);
api.state.selectedEvidence={{type:'table',sourceScope:'workspace',assetId:1,paperId:1}};
inspectorSep.listeners.pointerdown[0]({{currentTarget:inspectorSep,button:0,pointerId:11,clientX:1200,preventDefault:prevent}});inspectorSep.listeners.pointercancel[0]({{pointerId:11,preventDefault:prevent}});assert.equal(inspectorSep.captured,null);assert.equal(html.dataset.paneResizing,undefined);
inspectorSep.listeners.pointerdown[0]({{currentTarget:inspectorSep,button:0,pointerId:12,clientX:1200,preventDefault:prevent}});inspectorSep.listeners.lostpointercapture[0]({{pointerId:12,preventDefault:prevent}});assert.equal(html.dataset.paneResizing,undefined);
inspectorSep.listeners.keydown[0]({{currentTarget:inspectorSep,key:'End',shiftKey:false,preventDefault:prevent}});assert.equal(api.paneLayout.inspector.collapsed,true);assert(api.togglePane('inspector'));assert.equal(api.paneLayout.inspector.size,340);
api.state.selectedEvidence=null;
geometry=api.applyPaneLayout();groupSep.listeners.pointerdown[0]({{currentTarget:groupSep,button:0,pointerId:9,clientX:800,preventDefault:prevent}});groupSep.listeners.pointermove[0]({{pointerId:9,clientX:0,preventDefault:prevent}});groupSep.listeners.pointerup[0]({{pointerId:9,preventDefault:prevent}});assert.equal(api.paneLayout.editors.primaryCollapsed,true);assert.equal(primary.hidden,true);assert.equal(secondary.hidden,false);assert.equal(controller.collapseEditor('secondary'),false);
assert(api.togglePane('primary'),'primary toggle must restore');assert.equal(api.paneLayout.editors.primaryCollapsed,false,'primary expanded');assert(Math.abs(api.paneLayout.editors.split-.58)<.001,`split restored ${{api.paneLayout.editors.split}}`);
assert(controller.collapseEditor('primary'),'primary can collapse while secondary is usable');api.renderDocumentTabs();assert.equal(primary.hidden,true);tabs.close('evidence:b');api.renderDocumentTabs();assert.equal(api.paneLayout.editors.primaryCollapsed,false,'closing the last secondary tab repairs the primary editor');assert.equal(primary.hidden,false,'central editor must remain visible');assert.equal(secondary.hidden,true,'empty secondary editor must not occupy the workspace');tabs.open({{tabId:'evidence:b',kind:'evidence',ownerView:'paper',title:'B',identity:{{sourceScope:'workspace',entityType:'table',entityUid:'2'}}}},{{groupId:'secondary',pin:true}});api.renderDocumentTabs();
groupSep.listeners.pointerdown[0]({{currentTarget:groupSep,button:0,pointerId:13,clientX:800,preventDefault:prevent}});globalListeners.blur[0]({{preventDefault:prevent}});assert.equal(groupSep.captured,null);assert.equal(html.dataset.paneResizing,undefined);
controller.expandSide('context',{{persist:false}});api.applyPaneLayout();contextSep.listeners.pointerdown[0]({{currentTarget:contextSep,button:0,pointerId:14,clientX:244,preventDefault:prevent}});assert.equal(contextSep.captured,14);globalListeners.pointerup[0]({{pointerId:14,preventDefault:prevent}});assert.equal(contextSep.captured,null,'global pointerup must release pointer capture');assert.equal(html.dataset.paneResizing,undefined,'global pointerup must clear paneResizing');
api.setPaneLayoutValue('editor-groups',1);assert.equal(api.paneLayout.editors.secondaryCollapsed,true);groupSep.listeners.dblclick[0]();assert.equal(api.paneLayout.editors.secondaryCollapsed,false);assert(Math.abs(api.paneLayout.editors.split-.58)<.001);
const saved=JSON.parse(memory.get('fusion-pane-layout-v2'));assert.equal(saved.schema_version,'fusion-pane-layout-v2');assert(!JSON.stringify(saved).includes('evidence:a'));assert.deepEqual(Object.keys(saved).sort(),['context','editors','inspector','schema_version']);
const stateRef=api.paneLayout;memory.set('fusion-pane-layout-v2',JSON.stringify({{schema_version:'fusion-pane-layout-v2',context:{{collapsed:true,size:0,lastExpanded:310}},inspector:{{collapsed:false,size:400,lastExpanded:400}},editors:{{primaryCollapsed:false,secondaryCollapsed:false,split:.4,lastSplit:.4}}}}));assert.equal(api.readPaneLayout(),true);assert.strictEqual(api.paneLayout,stateRef);assert.equal(api.paneLayout.context.lastExpanded,310);assert.equal(api.paneLayout.editors.split,.4);
controller.expandSide('context',{{persist:false}});controller.expandSide('inspector',{{persist:false}});controller.expandEditor('secondary',{{persist:false}});globalThis.innerWidth=1280;api.state.view='paper';api.state.searchMode='precise';let coordinated=api.coordinateTaskLayout('runtime-dual');assert.equal(coordinated.secondaryCollapsed,false,'secondary editor remains visible');assert.equal(coordinated.inspectorDocked,false,'1280 dual editor releases inspector');assert.equal(coordinated.contextDocked,false,'1280 split temporarily releases context instead of squeezing both editors');assert.equal(coordinated.projection.inspector,'hidden');assert.equal(api.paneLayout.inspector.collapsed,false,'task projection must not change the user inspector state');assert.equal(api.paneLayout.context.collapsed,false,'task projection must not change the user context state');api.state.selectedEvidence={{type:'table',sourceScope:'workspace',assetId:1,paperId:1}};coordinated=api.coordinateTaskLayout('runtime-inspector-drawer');assert.equal(coordinated.projection.inspector,'drawer');assert.equal(html.style.values['--fusion-inspector-size'],'0px','drawer must not occupy a shell grid column');assert.equal(html.style.values['--fusion-inspector-drawer-size'],'400px','drawer keeps the user inspector width');api.state.selectedEvidence=null;api.state.view='personal';coordinated=api.coordinateTaskLayout('leave-paper');assert.equal(coordinated.contextDocked,true,'experiment restores its context pane at desktop width');assert.equal(coordinated.inspectorDocked,false,'the experiment inspector is selection-only');assert.equal(coordinated.secondaryCollapsed,true,'an unrelated secondary document is only transiently hidden');assert.equal(api.paneLayout.editors.secondaryCollapsed,false,'task projection does not close the stored secondary group');
const secondaryIdentity=tabs.activeTab('secondary').tabId,storedSecondaryCollapsed=api.paneLayout.editors.secondaryCollapsed;api.state.view='settings';api.coordinateTaskLayout('settings');api.renderDocumentTabs();assert.equal(secondary.hidden,true,'settings transiently hides secondary');assert.equal(inspector.hidden,true,'settings transiently hides inspector');assert.equal(tabs.activeTab('secondary').tabId,secondaryIdentity,'settings retains secondary tab identity');assert.equal(api.paneLayout.editors.secondaryCollapsed,storedSecondaryCollapsed,'settings does not mutate stored editor layout');api.state.view='paper';api.coordinateTaskLayout('leave-settings');api.renderDocumentTabs();assert.equal(secondary.hidden,false,'leaving settings restores secondary');assert.equal(tabs.activeTab('secondary').tabId,secondaryIdentity);
assert(controller.collapseEditor('primary'),'user may prefer the secondary group only');const storedBeforeTask=memory.get('fusion-pane-layout-v2');api.state.view='search';api.state.searchMode='librarian';api.state.librarianResultsOpen=true;coordinated=api.coordinateTaskLayout('librarian-results');api.renderDocumentTabs();assert.equal(primary.hidden,false,'task suppression must force the librarian primary surface visible without resetting storage');assert.equal(secondary.hidden,true,'librarian results transiently release the secondary group');assert.equal(api.paneLayout.editors.primaryCollapsed,true,'the user primary-collapse preference remains stored');assert.equal(api.paneLayout.editors.secondaryCollapsed,false);assert.equal(memory.get('fusion-pane-layout-v2'),storedBeforeTask,'task fallback must not rewrite localStorage');api.state.librarianResultsOpen=false;coordinated=api.coordinateTaskLayout('librarian-results-closed');api.renderDocumentTabs();assert.equal(primary.hidden,false,'librarian chat continues to own the primary surface');assert.equal(secondary.hidden,true,'closing results does not restore an unrelated editor beside the librarian');assert.equal(api.paneLayout.editors.primaryCollapsed,true,'task projection preserves the stored preference');assert.equal(api.paneLayout.editors.secondaryCollapsed,false);assert.equal(memory.get('fusion-pane-layout-v2'),storedBeforeTask);api.state.searchMode='precise';coordinated=api.coordinateTaskLayout('return-to-precise');api.renderDocumentTabs();assert.equal(primary.hidden,true,'leaving librarian restores the user primary-collapse preference');assert.equal(secondary.hidden,false,'leaving librarian restores the stored secondary group');controller.expandEditor('primary',{{persist:false}});
globalThis.innerWidth=1440;api.state.view='paper';api.state.searchMode='precise';api.state.selectedEvidence=null;assert.equal(api.togglePane('inspector'),false,'an empty inspector cannot be opened from a toolbar or command');tabs.focusGroup('primary');coordinated=api.coordinateTaskLayout('matrix-1440');assert.equal(coordinated.contextDocked,false,'1440 split releases context instead of forming a four-pane wall');assert.equal(coordinated.inspectorDocked,false,'1440 releases the less relevant inspector');assert.equal(coordinated.secondaryCollapsed,false);globalThis.innerWidth=900;coordinated=api.coordinateTaskLayout('matrix-900');assert.equal(coordinated.contextDocked,false,'900 uses the context drawer');assert.equal(coordinated.inspectorDocked,false);assert.equal(coordinated.projection.secondary,'single');assert.equal(coordinated.secondaryCollapsed,true,'compact mode shows only the active editor group');assert.equal(api.paneLayout.editors.secondaryCollapsed,false,'compact projection does not overwrite the saved editor state');
globalThis.innerWidth=800;let responsive=api.syncResponsivePaneLayout();assert.equal(responsive.narrow,true);assert.equal(groupSep.hidden,true);assert.equal(tabs.snapshot().tabs.find(tab=>tab.tabId==='evidence:b').groupId,'secondary');globalThis.innerWidth=1280;coordinated=api.coordinateTaskLayout('return-from-narrow');assert.equal(coordinated.inspectorDocked,false,'returning desktop does not resurrect an unrelated inspector');globalThis.innerWidth=800;responsive=api.syncResponsivePaneLayout();
globalThis.innerWidth=1600;responsive=api.syncResponsivePaneLayout();assert.equal(responsive.narrow,false);assert.equal(groupSep.hidden,false);assert.equal(tabs.activeTab('primary').tabId,'evidence:a');assert.equal(tabs.activeTab('secondary').tabId,'evidence:b');
const searchTab=tabs.open({{tabId:'evidence:search-b',kind:'evidence',ownerView:'search',title:'搜索证据 B',identity:{{sourceScope:'workspace',entityType:'table',entityUid:'3'}}}},{{groupId:'secondary',pin:true}});api.state.view='search';assert(api.activateDocumentTab(searchTab.tabId));assert.equal(tabs.snapshot().activeGroupId,'secondary');assert.equal(api.state.activeGroupByView.search,'secondary');
assert(api.switchView('settings',{{focus:false,activateTab:false}}));assert.equal(tabs.snapshot().activeGroupId,'secondary','settings must not persistently replace the active document group');assert.equal(primary.hidden,false,'settings projects its primary editor without mutating document focus');assert.equal(secondary.hidden,true);assert.equal(groupSep.hidden,true);assert.equal(secondaryToggle.attrs['aria-expanded'],'false');
assert(api.switchView('package',{{focus:false,activateTab:false}}));assert.equal(tabs.snapshot().activeGroupId,'secondary','package must also preserve the prior document group');assert.equal(primary.hidden,false);assert.equal(secondary.hidden,true);
assert(api.switchView('search',{{focus:false,activateTab:false}}));assert.equal(tabs.snapshot().activeGroupId,'secondary','returning to search restores its prior active group');assert.equal(primary.hidden,false);assert.equal(secondary.hidden,false);assert.equal(groupSep.hidden,false);assert.equal(secondaryToggle.attrs['aria-expanded'],'true');
globalThis.innerWidth=1000;responsive=api.syncResponsivePaneLayout();assert.equal(responsive.projection.secondary,'single');assert.equal(tabs.snapshot().activeGroupId,'secondary','compact projection preserves the active secondary identity');assert.equal(primary.hidden,true);assert.equal(secondary.hidden,false);assert.equal(groupSep.hidden,true);assert.equal(secondaryGroup.hidden,true,'compact mode uses one shared tab strip');assert(primaryTabs.innerHTML.includes('搜索证据 B'),'compact tab strip still exposes the active secondary tab');assert.equal(secondaryToggle.attrs['aria-expanded'],'true');
assert(api.switchView('settings',{{focus:false,activateTab:false}}));assert.equal(tabs.snapshot().activeGroupId,'secondary');assert.equal(primary.hidden,false,'single-editor settings projection must never go blank');assert.equal(secondary.hidden,true);assert.equal(secondaryToggle.attrs['aria-expanded'],'false');assert(api.switchView('search',{{focus:false,activateTab:false}}));assert.equal(tabs.snapshot().activeGroupId,'secondary');assert.equal(primary.hidden,true);assert.equal(secondary.hidden,false);
globalThis.innerWidth=1200;responsive=api.syncResponsivePaneLayout();assert.equal(responsive.projection.secondary,'docked');assert.equal(primary.hidden,false);assert.equal(secondary.hidden,false);assert.equal(groupSep.hidden,false);assert.equal(secondaryGroup.hidden,false);assert.equal(secondaryToggle.attrs['aria-expanded'],'true');
globalThis.innerWidth=720;responsive=api.syncResponsivePaneLayout();assert.equal(responsive.projection.secondary,'single');assert.equal(tabs.snapshot().activeGroupId,'secondary');assert.equal(primary.hidden,true);assert.equal(secondary.hidden,false);assert.equal(groupSep.hidden,true);assert(tabs.snapshot().tabs.some(tab=>tab.tabId==='evidence:search-b'&&tab.groupId==='secondary'),'narrow mode must not discard the secondary tab');
globalThis.innerWidth=1600;api.syncResponsivePaneLayout();api.switchView('paper',{{focus:false,activateTab:false}});tabs.close('evidence:search-b');tabs.activate('evidence:b');tabs.activate('evidence:a');
const legacyPersonal=tabs.open({{tabId:'personal-table:legacy',kind:'personal-table',ownerView:'personal',title:'旧实验表格标签',identity:{{sourceScope:'private',sourceId:'lab',entityType:'table',entityUid:'legacy'}}}},{{groupId:'secondary',pin:true}});assert(api.normalizeTabGroup(legacyPersonal));assert.equal(tabs.snapshot().tabs.find(tab=>tab.tabId===legacyPersonal.tabId).groupId,'primary','views with one editor migrate old secondary tabs into the primary group');tabs.close(legacyPersonal.tabId);tabs.activate('evidence:a');
memory.set('fusion-pane-layout-v2',JSON.stringify({{schema_version:'fusion-pane-layout-v2',context:{{collapsed:false,size:244,lastExpanded:244}},inspector:{{collapsed:false,size:340,lastExpanded:340}},editors:{{primaryCollapsed:true,secondaryCollapsed:true,split:0,lastSplit:.4}}}}));assert.equal(api.readPaneLayout(),false,'damaged both-collapsed layout must be rejected');api.renderEditorSurfaces();assert.equal(api.paneLayout.editors.primaryCollapsed,false);assert.equal(api.paneLayout.editors.secondaryCollapsed,false);assert.equal(primary.hidden,false);assert.equal(secondary.hidden,false);assert.equal(tabs.activeTab('primary').tabId,'evidence:a');assert.equal(tabs.activeTab('secondary').tabId,'evidence:b');
;(async()=>{{
  globalThis.innerWidth=1280;api.state.view='search';api.state.searchMode='precise';
  const row={{type:'item',title:'辐照温度',value:'873',unit:'K',meaning:'辐照温度',sourceScope:'workspace',sourceId:'workspace',entityUid:'91',itemId:91,paperId:56,page:8,pageEnd:8,articleTitle:'辐照研究',doi:'',locator:'',firstAuthor:'',correspondingAuthor:'',excerpt:'原文短摘录',quantities:[],variables:{{}},materials:[],conditions:'',methods:'',linkedItemCount:0,tags:[]}};
  api.state.searchResults=[row];const trigger=new El();trigger.isConnected=true;
  assert.equal(await api.openEvidenceDetail(0,trigger,{{preview:true}}),true,'first result click opens the secondary detail');
  const detail=tabs.activeTab('secondary'),tabCount=tabs.snapshot().tabs.filter(tab=>tab.tabId===detail.tabId).length,binding=tabs.requestBinding(detail.tabId);assert.equal(detail.payload.status,'ready');assert.equal(tabCount,1);
  tabs.rememberPresentation(detail.tabId,{{scrollTop:173,focusToken:'evidence-question'}});
  assert(api.togglePane('context'),'the user may temporarily reveal the context pane');assert.equal(api.workspaceReveal.surface,'context');assert.equal(secondary.hidden,true,'task reveal temporarily hides the secondary detail');
  assert(controller.collapseEditor('secondary',{{persist:false}}),'the stored secondary geometry can also be collapsed');api.renderDocumentTabs();assert.equal(secondary.hidden,true);
  assert.equal(await api.openEvidenceDetail(0,trigger,{{preview:true}}),true,'reselecting an existing detail reopens its group');
  const reopened=tabs.activeTab('secondary'),projection=api.coordinateTaskLayout('reselect-existing-detail');assert.equal(reopened.tabId,detail.tabId,'reselection reuses the same stable detail tab');assert.equal(tabs.snapshot().tabs.filter(tab=>tab.tabId===detail.tabId).length,1,'reselection must not duplicate the tab');assert.equal(api.workspaceReveal.surface,null,'stale context or inspector reveal no longer suppresses the requested detail');assert.equal(api.paneLayout.editors.secondaryCollapsed,false,'the requested editor group is expanded');assert.equal(secondary.hidden,false,'the secondary content is visible again');assert.equal(groupSep.hidden,false,'the splitter is visible with both editor groups');assert.equal(projection.contextDocked,false,'1280 detail layout releases the unrelated context pane');assert.equal(projection.inspectorDocked,false,'1280 detail layout releases the unrelated inspector');assert.equal(tabs.requestBinding(detail.tabId).generation,binding.generation,'a live existing tab is not re-requested');assert.equal(tabs.presentation(detail.tabId).scrollTop,173,'reselection preserves tab presentation state');assert.equal(tabs.snapshot().activeGroupId,'secondary');assert.equal(primary.hidden,false,'the primary result list remains available');
}})().catch(error=>{{console.error(error);process.exitCode=1}});
"""
        result = subprocess.run(["node", "-e", program], capture_output=True, text=True, check=False)
        self.assertEqual(result.returncode, 0, result.stderr)


if __name__ == "__main__":
    unittest.main()
