"""Cross-platform product distribution primitives for Auto Research."""

from .evidence_package import (
    ARESEARCH_FORMAT,
    ARESEARCH_FORMAT_VERSION,
    EvidencePackageError,
    ImportedEvidencePackage,
    VerifiedEvidencePackage,
    build_evidence_package,
    import_evidence_package,
    rollback_evidence_package,
    verify_evidence_package,
)
from .evidence_v12_export import plan_evidence_v12_export
from .official_package_store import (
    ACTIVE_SELECTOR_RELATIVE_PATH,
    EXPECTED_DISTRIBUTION_SCHEMA,
    ActiveOfficialPackage,
    default_active_state_path,
    import_official_evidence_package,
    open_active_official_repository,
    rollback_official_evidence_package,
)
from .portable_repository import (
    DATABASE_CONTRACT,
    DISTRIBUTION_SCHEMA_VERSION,
    OfficialEvidenceRepository,
    PortableExportPlan,
    PortableRepositoryError,
    PortableRepositoryExport,
    ReleasePolicy,
    audit_portable_repository,
    materialize_portable_repository,
    provenance_for_papers,
)
from .trusted_publishers import (
    TRUSTED_PUBLISHER_REGISTRY_VERSION,
    TrustedPublisher,
    TrustedPublisherPolicy,
    TrustedPublisherPolicyError,
    assert_trusted_package_identity,
    trusted_publisher_policy,
    trusted_public_keys,
    trusted_publishers,
)

__all__ = [
    "ARESEARCH_FORMAT",
    "ARESEARCH_FORMAT_VERSION",
    "EvidencePackageError",
    "ImportedEvidencePackage",
    "VerifiedEvidencePackage",
    "build_evidence_package",
    "import_evidence_package",
    "rollback_evidence_package",
    "verify_evidence_package",
    "DATABASE_CONTRACT",
    "DISTRIBUTION_SCHEMA_VERSION",
    "OfficialEvidenceRepository",
    "PortableExportPlan",
    "PortableRepositoryError",
    "PortableRepositoryExport",
    "ReleasePolicy",
    "audit_portable_repository",
    "materialize_portable_repository",
    "plan_evidence_v12_export",
    "provenance_for_papers",
    "ACTIVE_SELECTOR_RELATIVE_PATH",
    "EXPECTED_DISTRIBUTION_SCHEMA",
    "ActiveOfficialPackage",
    "default_active_state_path",
    "import_official_evidence_package",
    "open_active_official_repository",
    "rollback_official_evidence_package",
    "TRUSTED_PUBLISHER_REGISTRY_VERSION",
    "TrustedPublisher",
    "TrustedPublisherPolicy",
    "TrustedPublisherPolicyError",
    "assert_trusted_package_identity",
    "trusted_publisher_policy",
    "trusted_public_keys",
    "trusted_publishers",
]
