"""Runtime AI providers used by the released research application."""

from .deepseek import DeepSeekClient, DeepSeekSettings
from .openai_compatible import (
    AIProviderCapabilityError,
    AIProviderError,
    AIProviderNotConfigured,
    AIProviderResponseError,
    AIProviderUnavailableError,
    OpenAICompatibleClient,
    OpenAICompatibleSettings,
)
from .provider_registry import (
    ProviderCapabilities,
    TrustedProviderProfile,
    trusted_provider_profile,
    trusted_provider_public_catalog,
)
from .capability_verifier import (
    BackendCredentialResolver,
    OpenAICompatibleCapabilityVerifier,
)
from .consent import (
    AI_CONSENT_SCOPES,
    AI_CONSENT_TTL_SECONDS,
    DISCLOSURE_VERSIONS,
    AIConsentError,
    AIConsentService,
    ConsentClock,
    PreparedConsentBinding,
    SystemConsentClock,
)
from .prepared_actions import (
    CompositeContentSnapshotAuthority,
    ContentSnapshotAuthority,
    ContentUnit,
    PreparedActionClock,
    PreparedActionError,
    PreparedActionService,
    PreparedOutbound,
    RuntimeActionAuthority,
    SystemPreparedActionClock,
)
from .runtime_factory import RuntimeAIClientFactory, RuntimeCredentialResolver
from .runtime_factory import (
    AIExecutionLeaseAuthority,
    AIRuntimeBindingError,
    BoundCredentialResolver,
    BoundRuntimeAction,
)
from .business_actions import (
    BUSINESS_ACTION_SCOPES,
    AuthorizedCall,
    BusinessAIClientFactory,
    BusinessActionClock,
    BusinessActionAssembler,
    BusinessActionDraft,
    BusinessActionError,
    BusinessActionExecutor,
    BusinessPreparedActionRegistry,
    BusinessResultProjector,
    BudgetedBusinessAIClient,
    PreparedBusinessCall,
    SafeBusinessModelSettings,
    SystemBusinessActionClock,
)
from .desktop_controller import (
    DESKTOP_AI_ROUTES,
    ConsentProtectedAction,
    DesktopAIController,
    DesktopAIHTTPResponse,
    DesktopAIRequestContext,
    DesktopAIRoute,
    DesktopAISettings,
)

__all__ = [
    "DeepSeekClient",
    "DeepSeekSettings",
    "AIProviderError",
    "AIProviderNotConfigured",
    "AIProviderResponseError",
    "AIProviderUnavailableError",
    "AIProviderCapabilityError",
    "OpenAICompatibleClient",
    "OpenAICompatibleSettings",
    "ProviderCapabilities",
    "TrustedProviderProfile",
    "trusted_provider_profile",
    "trusted_provider_public_catalog",
    "BackendCredentialResolver",
    "OpenAICompatibleCapabilityVerifier",
    "AI_CONSENT_SCOPES",
    "AI_CONSENT_TTL_SECONDS",
    "DISCLOSURE_VERSIONS",
    "AIConsentError",
    "AIConsentService",
    "ConsentClock",
    "PreparedConsentBinding",
    "SystemConsentClock",
    "ContentSnapshotAuthority",
    "CompositeContentSnapshotAuthority",
    "ContentUnit",
    "PreparedActionClock",
    "PreparedActionError",
    "PreparedActionService",
    "PreparedOutbound",
    "RuntimeActionAuthority",
    "SystemPreparedActionClock",
    "RuntimeAIClientFactory",
    "RuntimeCredentialResolver",
    "AIRuntimeBindingError",
    "AIExecutionLeaseAuthority",
    "BoundCredentialResolver",
    "BoundRuntimeAction",
    "BUSINESS_ACTION_SCOPES",
    "AuthorizedCall",
    "BusinessAIClientFactory",
    "BusinessActionClock",
    "BusinessActionAssembler",
    "BusinessActionDraft",
    "BusinessActionError",
    "BusinessActionExecutor",
    "BusinessPreparedActionRegistry",
    "BusinessResultProjector",
    "BudgetedBusinessAIClient",
    "PreparedBusinessCall",
    "SafeBusinessModelSettings",
    "SystemBusinessActionClock",
    "DESKTOP_AI_ROUTES",
    "ConsentProtectedAction",
    "DesktopAIController",
    "DesktopAIHTTPResponse",
    "DesktopAIRequestContext",
    "DesktopAIRoute",
    "DesktopAISettings",
]
