"""Path-free application settings contracts."""

from .ai_provider import (
    AIProviderSelection,
    AIProviderSettingsError,
    AISettingsService,
    CredentialResolver,
)
from .desktop_settings import (
    AtomicDesktopSettingsStore,
    DesktopPreferences,
    DesktopSettingsError,
    DesktopSettingsService,
    DesktopSettingsSnapshot,
)
from .ai_runtime_state import (
    AIRuntimePublicState,
    AIRuntimeStateError,
    AIRuntimeStateService,
    AtomicAIRuntimeStateStore,
    AI_VERIFICATION_TTL_SECONDS,
    BackendCredentialState,
    CredentialStateProvider,
    Clock,
    ModelCapabilityResult,
    ProviderCapabilityVerifier,
    ResolvedAIRuntime,
    RuntimeActionBinding,
    SystemClock,
    VerificationAttestationSigner,
)
from .ai_desktop_service import (
    AI_CAPABILITY_TEST_CACHE_SECONDS,
    AI_CAPABILITY_TEST_COOLDOWN_SECONDS,
    AI_CAPABILITY_TEST_CONSENT_VERSION,
    AIDesktopClock,
    AIDesktopService,
    AIDesktopServiceError,
    CredentialManager,
    SystemAIDesktopClock,
)

__all__ = [
    "AIProviderSelection",
    "AIProviderSettingsError",
    "AISettingsService",
    "CredentialResolver",
    "AtomicDesktopSettingsStore",
    "DesktopPreferences",
    "DesktopSettingsError",
    "DesktopSettingsService",
    "DesktopSettingsSnapshot",
    "AIRuntimePublicState",
    "AIRuntimeStateError",
    "AIRuntimeStateService",
    "AtomicAIRuntimeStateStore",
    "AI_VERIFICATION_TTL_SECONDS",
    "BackendCredentialState",
    "CredentialStateProvider",
    "Clock",
    "ModelCapabilityResult",
    "ProviderCapabilityVerifier",
    "ResolvedAIRuntime",
    "RuntimeActionBinding",
    "SystemClock",
    "VerificationAttestationSigner",
    "AI_CAPABILITY_TEST_CONSENT_VERSION",
    "AI_CAPABILITY_TEST_CACHE_SECONDS",
    "AI_CAPABILITY_TEST_COOLDOWN_SECONDS",
    "AIDesktopClock",
    "AIDesktopService",
    "AIDesktopServiceError",
    "CredentialManager",
    "SystemAIDesktopClock",
]
